### ISSUE TITLE
Consider using the platform/target now available in litex

### ISSUE THREAD

**Issue by TomKeddie** [trabucayre/litexOnColorlightLab004#1]
Hi, Nice stuff you have here.  I wasn't sure if you knew support for the colorlight is now in litex.
 
See https://twitter.com/enjoy_digital/status/1220004677217144834

https://github.com/litex-hub/litex-boards/blob/master/litex_boards/platforms/colorlight_5a_75b.py

Cheers,
Tom

**Comment by TomKeddie** [comment]
See also https://github.com/litex-hub/litex-boards/pull/50

**Comment by trabucayre** [comment]
You have right. I just pushed modification to use litex-boards platform. Now serial is added as extension.

Cheers,
Gwen
